#!/bin/bash

BASE_URL=${!#}

##引数チェックを入れよう

if [ $1 = "login" ]; then
  curl ${BASE_URL}
  exit 0
elif [ $1 = "overview" ]; then
  curl ${BASE_URL}
  exit 0
else
  echo "$1: Invalid command"
  exit 1
fi
