#!/bin/sh

if [ $# -ne 5 ]; then
  exit 1
fi

BASE_URL=${!#}

if [ "$1" = "login" ]; then
  curl $BASE_URL
  exit 0
elif [ "$1" = "overview" ]; then
  curl $BASE_URL/overview
  exit 0
elif [ "$1" = "perfmon" ]; then
  curl $BASE_URL/perfmon
  exit 0
else
  exit 1
fi
